# How to normalize?

Now that we have the new data preprocessing, we can tackle the issue of normalization.

For now these options should be available:
- PCA
- standard mean/std
- max_rs (so essentially std by var and combinations thereof)

I guess I should also look at how to then use that in a data generator.

In [2]:
from cbrain.imports import *

## Load preprocessed data.

In [3]:
DATADIR = '/local/S.Rasp/preprocessed_data/'

In [4]:
!ls -lh $DATADIR

total 358G
-rw-r--r-- 1 S.Rasp ls-craig  18K Jan 24 14:34 000_norm.nc
-rw-r--r-- 1 S.Rasp ls-craig 2.2G Jan 24 14:32 000_train.nc
-rw-r--r-- 1 S.Rasp ls-craig 2.1G Jan 24 14:33 000_train_shuffle.nc
-rw-r--r-- 1 S.Rasp ls-craig 2.2G Jan 24 14:33 000_valid.nc
-rw-r--r-- 1 S.Rasp ls-craig 7.5G Jan 24 11:21 001_train.nc
-rw-r--r-- 1 S.Rasp ls-craig 7.3G Jan 24 11:21 001_train_shuffle.nc
-rw-r--r-- 1 S.Rasp ls-craig 6.8G Jan 24 11:25 001_valid.nc
-rw-r--r-- 1 S.Rasp ls-craig  54G Jan 10 16:22 32_col_engy_ess_1y_train_features.nc
-rw-r--r-- 1 S.Rasp ls-craig  54G Jan 10 17:08 32_col_engy_ess_1y_train_shuffle_features.nc
-rw-r--r-- 1 S.Rasp ls-craig  38G Jan 10 17:08 32_col_engy_ess_1y_train_shuffle_targets.nc
-rw-r--r-- 1 S.Rasp ls-craig  38G Jan 10 16:32 32_col_engy_ess_1y_train_targets.nc
-rw-r--r-- 1 S.Rasp ls-craig 5.3G Jan  8 12:49 32_col_engy_ess_3d_train_features.nc
-rw-r--r-- 1 S.Rasp ls-craig  24K Jan  8 12:48 32_col_engy_ess_3d_train_norm.nc
-rw-r--r-- 1 S.Rasp ls-craig 5.3G Jan  8

In [5]:
trn = xr.open_dataset(DATADIR + '000_train.nc')

In [5]:
trn

<xarray.Dataset>
Dimensions:    (sample: 3530752, var_names: 159)
Coordinates:
  * var_names  (var_names) object 'TBP' 'TBP' 'TBP' ... 'FLNT' 'FLNS' 'PRECT'
    time       (sample) int64 ...
    lat        (sample) float64 ...
    lon        (sample) float64 ...
Dimensions without coordinates: sample
Data variables:
    vars       (sample, var_names) float32 ...

In [6]:
trn.var_names

<xarray.DataArray 'var_names' (var_names: 159)>
array(['TBP', 'TBP', 'TBP', 'TBP', 'TBP', 'TBP', 'TBP', 'TBP', 'TBP', 'TBP',
       'TBP', 'TBP', 'TBP', 'TBP', 'TBP', 'TBP', 'TBP', 'TBP', 'TBP', 'TBP',
       'TBP', 'TBP', 'TBP', 'TBP', 'TBP', 'TBP', 'TBP', 'TBP', 'TBP', 'TBP',
       'QBP', 'QBP', 'QBP', 'QBP', 'QBP', 'QBP', 'QBP', 'QBP', 'QBP', 'QBP',
       'QBP', 'QBP', 'QBP', 'QBP', 'QBP', 'QBP', 'QBP', 'QBP', 'QBP', 'QBP',
       'QBP', 'QBP', 'QBP', 'QBP', 'QBP', 'QBP', 'QBP', 'QBP', 'QBP', 'QBP',
       'VBP', 'VBP', 'VBP', 'VBP', 'VBP', 'VBP', 'VBP', 'VBP', 'VBP', 'VBP',
       'VBP', 'VBP', 'VBP', 'VBP', 'VBP', 'VBP', 'VBP', 'VBP', 'VBP', 'VBP',
       'VBP', 'VBP', 'VBP', 'VBP', 'VBP', 'VBP', 'VBP', 'VBP', 'VBP', 'VBP',
       'PS', 'SOLIN', 'SHFLX', 'LHFLX', 'TPHYSTND', 'TPHYSTND', 'TPHYSTND',
       'TPHYSTND', 'TPHYSTND', 'TPHYSTND', 'TPHYSTND', 'TPHYSTND', 'TPHYSTND',
       'TPHYSTND', 'TPHYSTND', 'TPHYSTND', 'TPHYSTND', 'TPHYSTND', 'TPHYSTND',
       'TPHYSTND', 'TPHYS

## Compute standard normalization arrays

In [41]:
# First create a norm dataset
# Mean, std, etc will have dimensions var_names
norm_ds = xr.Dataset()

In [42]:
norm_ds

<xarray.Dataset>
Dimensions:  ()
Data variables:
    *empty*

In [15]:
mean = trn.vars.mean(dim='sample')

In [16]:
mean

<xarray.DataArray 'vars' (var_names: 159)>
array([ 2.289433e+02,  2.178566e+02,  1.987313e+02,  2.180804e+02,
        2.155468e+02,  2.095004e+02,  2.065618e+02,  2.053417e+02,
        2.047591e+02,  2.045300e+02,  2.049989e+02,  2.071436e+02,
        2.086929e+02,  2.164163e+02,  2.216183e+02,  2.297919e+02,
        2.385379e+02,  2.475247e+02,  2.542547e+02,  2.598487e+02,
        2.625759e+02,  2.650574e+02,  2.691584e+02,  2.715526e+02,
        2.732425e+02,  2.747398e+02,  2.764053e+02,  2.780224e+02,
        2.805325e+02,  2.824123e+02,  1.700770e-06,  1.672413e-06,
        1.382968e-06,  1.476775e-06,  1.424974e-06,  1.374307e-06,
        1.372885e-06,  1.414201e-06,  1.548541e-06,  2.014882e-06,
        3.756644e-06,  8.605848e-06,  1.979210e-05,  4.259874e-05,
        8.878949e-05,  1.750205e-04,  3.230596e-04,  5.727612e-04,
        9.818296e-04,  1.574560e-03,  2.375034e-03,  3.477780e-03,
        4.781717e-03,  5.585611e-03,  6.171478e-03,  6.706584e-03,
        7.143286e-0

In [43]:
norm_ds['mean'] = mean

In [44]:
norm_ds

<xarray.Dataset>
Dimensions:    (var_names: 159)
Coordinates:
  * var_names  (var_names) object 'TBP' 'TBP' 'TBP' ... 'FLNT' 'FLNS' 'PRECT'
Data variables:
    mean       (var_names) float32 228.94325 217.85664 ... 3.147634e-08

In [ ]:
# Now for the by_var variables
# First need to add a new coordinate

In [20]:
from collections import OrderedDict

In [21]:
var_list = list(OrderedDict.fromkeys(trn.var_names.values))

In [22]:
mean_by_var = []
std_by_var = []
for var in var_list:
    mean_by_var.append(trn.vars[:, trn.var_names == var].mean().values)
    std_by_var.append(trn.vars[:, trn.var_names == var].std().values)

In [39]:
norm_ds['mean_by_var'] = xr.DataArray(mean_by_var, coords={'var_names_single': np.array(var_list).astype('object')}, dims=['var_names_single'])

In [40]:
norm_ds

<xarray.Dataset>
Dimensions:           (var_names: 159, var_names_single: 14)
Coordinates:
  * var_names         (var_names) object 'TBP' 'TBP' 'TBP' ... 'FLNS' 'PRECT'
  * var_names_single  (var_names_single) object 'TBP' 'QBP' ... 'FLNS' 'PRECT'
Data variables:
    mean              (var_names) float32 228.94325 217.85664 ... 3.147634e-08
    mean_by_var       (var_names_single) float32 239.50552 ... 3.1559964e-08

## Check out output of script

In [9]:
norm = xr.open_dataset('/local/S.Rasp/preprocessed_data/000_norm.nc')

In [10]:
norm

<xarray.Dataset>
Dimensions:           (var_names: 159, var_names_single: 14)
Coordinates:
  * var_names         (var_names) object 'TBP' 'TBP' 'TBP' ... 'FLNS' 'PRECT'
  * var_names_single  (var_names_single) object 'TBP' 'QBP' ... 'FLNS' 'PRECT'
Data variables:
    mean              (var_names) float32 ...
    std               (var_names) float32 ...
    min               (var_names) float32 ...
    max               (var_names) float32 ...
    std_by_var        (var_names_single) float32 ...

## Write a new data generator that normalizes

What needs to happen here? 

1. Open dataset (h5py or xarray? do speed comparison)
2. 

Use keras iterator base class?

In [93]:
import tensorflow as tf

In [101]:
inputs = ['TBP', 'QBP', 'VBP', 'PS', 'SOLIN', 'SHFLX', 'LHFLX']
outputs = ['TPHYSTND', 'PHQ', 'FSNT', 'FSNS', 'FLNT', 'FLNS', 'PRECT']

In [23]:
input_idxs = trn.var_names == inputs[0]
input_idxs

<xarray.DataArray 'var_names' (var_names: 159)>
array([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, 

In [24]:
for v in inputs[1:]:
    input_idxs = np.bitwise_or(input_idxs, trn.var_names == v)

In [25]:
input_idxs

<xarray.DataArray 'var_names' (var_names: 159)>
array([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, 

In [66]:
DT = 1800.
L_V = 2.501e6   # Latent heat of vaporization
L_I = 3.337e5   # Latent heat of freezing
L_S = L_V + L_I # Sublimation
C_P = 1.00464e3 # Specific heat capacity of air at constant pressure
G = 9.80616
P0 = 1e5
conversion_dict = {
    'TPHYSTND': C_P,
    'TPHY_NOKE': C_P,
    'TPHYSTND_NORAD': C_P,
    'PHQ': L_S,
    'PHCLDLIQ' : L_S,
    'PHCLDICE' : L_S,
    'SPDT': C_P,
    'SPDQ': L_V,
    'QRL': C_P,
    'QRS': C_P,
    'PRECT': 1e3*24*3600 * 2e-2,
    'TOT_PRECL': 24*3600 * 2e-2,
    'TOT_PRECS': 24*3600 * 2e-2,
    'PRECS': 1e3*24*3600 * 2e-2,
    'FLUT': 1. * 1e-5,
    'FSNT': 1. * 1e-3,
    'FSDS': -1. * 1e-3,
    'FSNS': -1. * 1e-3,
    'FLNT': -1. * 1e-3,
    'FLNS': 1. * 1e-3,
    'QAP': L_S/DT,
    'QCAP': L_S/DT,
    'QIAP': L_S/DT
}

In [143]:
class DataGenerator(tf.keras.utils.Sequence):
    """https://stanford.edu/~shervine/blog/keras-how-to-generate-data-on-the-fly"""
    def __init__(self, data_fn, input_vars, output_vars, 
                 norm_fn=None, input_transform=None, output_transform=None,
                 batch_size=1024, shuffle=True):
        # Just copy over the attributes
        self.data_fn, self.norm_fn = data_fn, norm_fn
        self.input_vars, self.output_vars = input_vars, output_vars
        self.batch_size, self.shuffle = batch_size, shuffle
        
        # Open datasets
        self.data_ds = xr.open_dataset(data_fn)
        if not norm_fn is None: self.norm_ds = xr.open_dataset(norm_fn)
        
        # Compute number of samples and batches
        self.n_samples = self.data_ds.vars.shape[0]
        self.n_batches = int(np.floor(self.n_samples) / self.batch_size)
        
        # Get input and output variable indices
        self.input_idxs = return_var_idxs(self.data_ds, input_vars)
        self.output_idxs = return_var_idxs(self.data_ds, output_vars)
        self.n_inputs, self.n_outputs = int(self.input_idxs.sum()), int(self.output_idxs.sum())
        
        
        # Initialize input and output normalizers/transformers
        if input_transform is None: self.input_transform = Normalizer()
        elif input_transform == 'standard': self.input_transform = StandardNormalizer(self.norm_ds, input_vars)
        elif input_transform == 'max_rs': self.input_transform = MaxRSNormalizer(self.norm_ds, input_vars)
        else: self.input_transform = input_transform   # Assume an initialized normalizer is passed
            
        if output_transform is None: self.output_transform = Normalizer()
        elif type(output_transform) is dict: 
            self.output_transform = DictNormalizer(self.norm_ds, output_vars, output_transform)
        else: self.output_transform = output_transform   # Assume an initialized normalizer is passed
            
        # Now close the xarray file and load it as an h5 file instead
        # This significantly speeds up the reading of the data... 
        self.data_ds.close()
        self.data_ds = h5py.File(data_fn, 'r')

        
    def __len__(self):
        return self.n_batches
    
    def __getitem__(self, index):
        # Compute start and end indices for batch
        start_idx = index * self.batch_size
        end_idx = start_idx + self.batch_size
        
        # Grab batch from data
        batch = self.data_ds['vars'][start_idx:end_idx]
        
        # Split into inputs and outputs
        X = batch[:, self.input_idxs]
        Y = batch[:, self.output_idxs]
        
        # Normalize
        X = self.input_transform.transform(X)
        Y = self.output_transform.transform(Y)
        
        return X, Y
    
    def on_epoch_end(self):
        self.indices = np.arange(self.n_batches)
        if self.shuffle: np.random.shuffle(indices)
            

In [159]:
??return_var_idxs

In [157]:
class Normalizer(object):
    def __init__(self):
        pass
    
    def transform(x):
        return x

class StandardNormalizer(Normalizer):
    def __init__(self, norm_ds, var_list):
        var_idxs = return_var_idxs(norm_ds, var_list)
        self.mean = norm_ds['mean'].values[var_idxs]
        self.std = norm_ds['std'].values[var_idxs]
        
    def transform(self, x):
        return (x - self.mean) / self.std
    
class MaxRSNormalizer(Normalizer):
    def __init__(self, norm_ds, var_list):
        var_idxs = return_var_idxs(norm_ds, var_list)
        self.mean = norm_ds['mean'].values[var_idxs]
        rang = norm_ds['max'][var_idxs] - norm_ds['min'][var_idxs]
        std_by_var = rang.copy()
        for v in var_list:
            std_by_var[std_by_var.var_names == v] = norm_ds['std_by_var'][norm_ds.var_names_single == v]
        self.maxrs = np.maximum(rang, std_by_var).values
        
    def transform(self, x):
        return (x - self.mean) / self.maxrs

class DictNormalizer(Normalizer):
    def __init__(self, norm_ds, var_list, dic):
        var_idxs = return_var_idxs(norm_ds, var_list)
        var_names = norm_ds.var_names[var_idxs].copy()
        scale = np.zeros(var_names.shape).astype('float32')
        for i, v in enumerate(list(var_names.values)):
            scale[i] = dic[v]
        self.scale = scale
        
    def transform(self, x):
        return x * self.scale
    
    def inverse_transform(self, x):
        return x / self.scale
        

In [146]:
gen = DataGenerator(DATADIR + '000_train.nc', inputs, outputs, DATADIR + '000_norm.nc', input_transform='max_rs', 
                    output_transform=conversion_dict, shuffle=False)

In [147]:
gen.n_inputs, gen.n_outputs

(94, 65)

In [148]:
gen.input_idxs.sum()

<xarray.DataArray 'var_names' ()>
array(94)

In [149]:
gen.output_idxs

<xarray.DataArray 'var_names' (var_names: 159)>
array([False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, 

In [150]:
x, y = next(iter(gen))

In [156]:
x.dtype

dtype('float32')

### profiling

In [127]:
def prof():
    for i in range(100):
        gen.__getitem__(i)

In [133]:
def prof2():
    for i in range(100):
        gen2.__getitem__(i)

In [122]:
%load_ext line_profiler

In [140]:
%lprun -f gen2.__getitem__ prof2()

Much much fast using h5py

## Train a test neural network

In [100]:
from tensorflow.keras.layers import *

In [117]:
inp = Input(shape=(gen.n_inputs,))
x = Dense(128, activation='elu')(inp)
x = Dense(gen.n_outputs)(x)
model = tf.keras.models.Model(inp, x)

In [118]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         (None, 94)                0         
_________________________________________________________________
dense_4 (Dense)              (None, 128)               12160     
_________________________________________________________________
dense_5 (Dense)              (None, 65)                8385      
Total params: 20,545
Trainable params: 20,545
Non-trainable params: 0
_________________________________________________________________


In [119]:
model.compile('adam', 'mse')

In [151]:
model.fit_generator(gen)

Epoch 1/1
3448/3448 [==============================] - 20s 6ms/step - loss: 0.0028


In [152]:
model.fit_generator(gen, use_multiprocessing=True, workers=2)

Epoch 1/1
3448/3448 [==============================] - 17s 5ms/step - loss: 0.0028


In [153]:
model.fit_generator(gen, use_multiprocessing=True, workers=10)

Epoch 1/1
3448/3448 [==============================] - 17s 5ms/step - loss: 0.0027


In [48]:
norm.transform(x)

array([[ 0.7307177 ,  0.7395819 ,  1.0879064 , ..., -0.76381034,
        -0.8114089 ,  0.37327787],
       [ 0.730547  ,  0.7398344 ,  1.0878801 , ..., -0.7627074 ,
        -0.8103464 ,  0.37378797],
       [ 0.7303852 ,  0.74008775,  1.0880003 , ..., -0.7616356 ,
        -0.80933475,  0.37457484],
       ...,
       [ 0.7090288 ,  0.7769988 ,  1.2447591 , ..., -0.74259055,
        -0.8132322 , -0.7393508 ],
       [ 0.70754194,  0.7722932 ,  1.2415448 , ..., -0.71721876,
        -0.78374076, -0.7425638 ],
       [ 0.71111214,  0.76260144,  1.2401541 , ..., -0.7136309 ,
        -0.77401555, -0.74302304]], dtype=float32)

In [28]:
trn.vars.shape

(3530752, 159)

In [1]:
inputs = ['TBP', 'SOLIN']
outputs = ['TPHYSTND', 'PRECT']

In [8]:
trn

<xarray.Dataset>
Dimensions:    (sample: 3530752, var_names: 159)
Coordinates:
  * var_names  (var_names) object 'TBP' 'TBP' 'TBP' ... 'FLNT' 'FLNS' 'PRECT'
    time       (sample) int64 ...
    lat        (sample) float64 ...
    lon        (sample) float64 ...
Dimensions without coordinates: sample
Data variables:
    vars       (sample, var_names) float32 ...

In [11]:
norm

<xarray.Dataset>
Dimensions:           (var_names: 159, var_names_single: 14)
Coordinates:
  * var_names         (var_names) object 'TBP' 'TBP' 'TBP' ... 'FLNS' 'PRECT'
  * var_names_single  (var_names_single) object 'TBP' 'QBP' ... 'FLNS' 'PRECT'
Data variables:
    mean              (var_names) float32 ...
    std               (var_names) float32 ...
    min               (var_names) float32 ...
    max               (var_names) float32 ...
    std_by_var        (var_names_single) float32 ...